# Add CI label for any CI changes
CI:
  - ".github/**/*"
# Add crate-respective labels
crate-bus-mapping:
  - bus-mapping/**/*
crate-circuit-benchmarks:
  - circuit-benchmarks/**/*
crate-eth-types:
  - eth-types/**/*
crate-external-tracer:
  - external-tracer/**/*
crate-gadgets:
  - gadgets/**/*
crate-geth-utils:
  - geth-utils/**/*
crate-integration-tests:
  - integration-tests/**/*
crate-mock:
  - mock/**/*
crate-prover:
  - prover/**/*
crate-zkevm-circuits:
  - zkevm-circuits/src/**/*

# Add 'T-opcode' to any changes related to opcodes in `bus-mapping` or `zkevm-circuits`.
T-opcode:
  - any:
      [
        "zkevm-circuits/src/evm_circuit/execution/**/*",
        "bus-mapping/src/evm/opcodes/**/*",
      ]

# Add 'T-bench' to any changes related to benchmarks in `circuit-benchmarks`.
T-bench:
  - circuit-benchmarks/**/*
