use ethers_core::types::{Bloom, Log};
use rlp::Encodable;

/// EVM log's receipt.
#[derive(Clone, Debug, Default)]
pub struct Receipt {
    /// Denotes the ID of the tx.
    pub id: usize,
    /// Denotes whether or not the tx was executed successfully.
    pub status: u8,
    /// Denotes the cumulative gas used by the tx execution.
    pub cumulative_gas_used: u64,
    /// Represents the 256-bytes bloom filter.
    pub bloom: Bloom,
    /// List of logs generated by the tx.
    pub logs: Vec<Log>,
}

impl Encodable for Receipt {
    fn rlp_append(&self, s: &mut rlp::RlpStream) {
        s.begin_list(4);
        s.append(&self.status);
        s.append(&self.cumulative_gas_used);
        s.append(&self.bloom);
        s.begin_list(self.logs.len());
        for log in self.logs.iter() {
            s.begin_list(3);
            s.append(&log.address);
            s.append_list(&log.topics);
            s.append(&log.data.0);
        }
    }
}
