.PHONY: download-setup

# Could be called as `make download-setup -e degree=DEGREE params_dir=PARAMS_DIR`.
# As default `degree=26` and `params_dir=./test_params`.
download-setup:
	sh download_setup.sh ${degree} ${params_dir}
